#!/command/with-contenv bash
set -e
echo "--- S6 Service: Starting Privoxy ---"
# Configure Privoxy just before starting it
PRIVOXY_CONFIG_FILE="/etc/privoxy/config"
cp "/etc/privoxy/privoxy.conf.template" "${PRIVOXY_CONFIG_FILE}"
sed -i "s|__LOG_LEVEL__|${PRIVOXY_LOG_LEVEL:-0}|g" "${PRIVOXY_CONFIG_FILE}"

# Use exec to hand control over to privoxy
exec privoxy --no-daemon "${PRIVOXY_CONFIG_FILE}"
